# -*- coding: utf-8 -*-
"""Geographical plot using folium.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nhh1_tCd8lvyZCx_vsyNVSX6iAY58MAS
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import folium as fo
# %matplotlib inline

map = fo.Map()

map

x = fo.FeatureGroup(name='My Map')

x.add_child(fo.Marker(location=[27.1750,78.0422] , popup='hey' , icon=fo.Icon(color='blue')))

map.add_child(x)

for lat,lon in ([34,53],[24,-50],[90,-68]):
    x.add_child(fo.Marker(location=[lat,lon] ,
                          popup='hey' , icon=fo.Icon(color='red')))

map.add_child(x)

volcano = pd.read_csv('239.volcano.csv')

lat_vo = list(volcano['Latitude'])
lon_vo = list(volcano['Longitude'])
name_vo = list(volcano['Name'])

vol = fo.FeatureGroup(name='My Map')

for lat,lon,name in zip(lat_vo,lon_vo,name_vo):
    vol.add_child(fo.Marker(location=[lat,lon] ,
                          popup=name , icon=fo.Icon(color='red')))

map.add_child(vol)

vol.add_child(fo.GeoJson(data=(open('240.world.json','r',encoding='utf-8-sig').read())))

map.add_child(vol)

popu = pd.read_csv('241.us cities pop.csv')

popu.head()

lat_po = list(popu['lat'])
lon_po = list(popu['lon'])
name_po = list(popu['name'])
pop_po = list(popu['pop'])

po = fo.FeatureGroup(name='My Map')

def mar(popu):
    if(popu>35000):
        return 'red'
    elif(popu>10000 and popu<=35000):
        return 'blue'
    else:
        return 'green'

#for lat,lon,name,pop in zip(lat_po,lon_po,name_po,pop_po):
 #   po.add_child(fo.Marker(location=[lat,lon],popup=[pop,name] , 
  #                        icon=fo.Icon(color=mar(pop))))

# map.add_child(po)